#!/usr/bin/env python3
"""Talent tool-reference lint — does a bundle request real, current Oteny tools?

A companion to ``lint_upgrade_safe.py`` (kept separate so that gate stays a pure,
copyable upgrade-safety check). This one reads the published tool catalog
(``../references/tools-catalog.json``, generated by Oteny) and checks a Talent's
``agent-profile.yaml`` against it:

FAIL (blocks the gate):
  * **Stale tool claim** — a tool the bundle marks ``stubbed`` (in ``agent-profile.yaml``
    ``tools.stubbed`` or ``required_artifacts.yaml`` ``stubbed``) that is in fact **live**
    in the Oteny catalog. This is the rule that catches the real bug class — a Talent
    telling owners a tool is "not configured" long after it shipped. Don't stub a live tool.

WARN (surfaced, never blocks):
  * **Unknown requested tool** — a name in ``tools.required`` that is not a known Oteny
    first-party tool. It may be **bundle-provided** (a tool the Talent ships itself, e.g. a
    Yahoo-Finance ``live_tape`` script) — that is legitimate — or a typo. We can't tell, so
    we surface it rather than fail.
  * **Unknown toolset** — a name in ``toolset_contribution`` that is not a known Oteny
    built-in toolset (likely a typo).

Stdlib only — the talents CI runs bare Python 3.12 with no pip install (mirrors
``lint_upgrade_safe.py``), so ``agent-profile.yaml`` is parsed with a small regex extractor,
not PyYAML.

Usage:
    python3 lint_tools.py <bundle_dir> [<bundle_dir> ...] [--json] [--catalog PATH]
Exits non-zero if any bundle has a FAIL (a stale claim). WARNs never affect the exit code.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# The published catalog lives next to this script's bundle, under references/.
_DEFAULT_CATALOG = Path(__file__).resolve().parent.parent / "references" / "tools-catalog.json"


def _load_catalog(path: Path) -> dict:
    """Read the generated tool catalog → allow-lists + the live set.

    Returns ``{"required": {names}, "toolset": {names}, "live": {names}}``.
    """
    data = json.loads(path.read_text())
    tools = data.get("tools", [])
    required, toolset, live = set(), set(), set()
    for t in tools:
        name = t.get("requestable_name") or t.get("name")
        if not name:
            continue
        if t.get("request_via") == "toolset_contribution":
            toolset.add(name)
        else:
            required.add(name)
        if t.get("status") == "live":
            live.add(name)
    return {"required": required, "toolset": toolset, "live": live}


def _yaml_list(text: str, key: str) -> list[str]:
    """Every value of ``key`` as a YAML list — flow (``key: [a, b]``) AND block
    (``key:\\n  - a``) forms, across ALL occurrences of the key (``required_artifacts.yaml``
    repeats ``stubbed:`` once per artifact kind). Strips quotes and trailing ``# comments``.
    A tiny stdlib substitute for PyYAML (the CI has no pip)."""
    items: list[str] = []
    # Flow lists: key: [a, b, c]
    for m in re.finditer(rf"(?m)^[ \t]*{re.escape(key)}:[ \t]*\[(.*?)\]", text):
        items += [p.strip().strip("'\"") for p in m.group(1).split(",") if p.strip()]
    # Block lists: key:\n  - a\n  - b
    for m in re.finditer(rf"(?m)^([ \t]*){re.escape(key)}:[ \t]*(?:#.*)?$", text):
        indent = len(m.group(1))
        for line in text[m.end():].splitlines():
            if not line.strip():
                continue
            stripped = line.lstrip()
            cur = len(line) - len(stripped)
            if stripped.startswith("- ") and cur > indent:
                items.append(stripped[2:].split("#", 1)[0].strip().strip("'\""))
            else:
                break
    return [i for i in items if i]


def lint_bundle(bundle: Path, catalog: dict) -> tuple[list[str], list[str]]:
    """Return ``(violations, warnings)`` for one bundle dir."""
    violations: list[str] = []
    warnings: list[str] = []
    profile = bundle / "agent-profile.yaml"
    if not profile.is_file():
        return violations, warnings  # not a Talent profile — nothing to check
    prof_text = profile.read_text(errors="ignore")

    required = _yaml_list(prof_text, "required")
    toolsets = _yaml_list(prof_text, "toolset_contribution")
    stubbed = list(_yaml_list(prof_text, "stubbed"))
    ra = bundle / "required_artifacts.yaml"
    if ra.is_file():
        stubbed += _yaml_list(ra.read_text(errors="ignore"), "stubbed")

    # FAIL — a stubbed tool that is actually live in the Oteny catalog (the stale-claim bug).
    for name in dict.fromkeys(stubbed):  # de-dupe, preserve order
        if name in catalog["live"]:
            violations.append(
                f"stubs tool '{name}', but it is LIVE in the Oteny catalog — don't stub a "
                "live tool (degrade gracefully instead, or drop it from `stubbed`)"
            )

    # WARN — a requested first-party tool not in the catalog (bundle-provided? typo?).
    known_first_party = catalog["required"]
    for name in dict.fromkeys(required):
        if name not in known_first_party and name not in catalog["toolset"]:
            warnings.append(
                f"requests tool '{name}' which is not a known Oteny tool — fine if your "
                "Talent ships it itself; otherwise check for a typo (see references/tools-catalog.md)"
            )

    # WARN — an unknown toolset in toolset_contribution.
    for name in dict.fromkeys(toolsets):
        if name not in catalog["toolset"]:
            warnings.append(
                f"contributes toolset '{name}' which is not a known Oteny toolset "
                "(check for a typo; see references/tools-catalog.md)"
            )
    return violations, warnings


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Talent tool-reference lint (stale-claim gate)")
    ap.add_argument("bundles", nargs="+", help="bundle directories to lint")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--catalog", default=str(_DEFAULT_CATALOG),
                    help="path to the generated tools-catalog.json")
    args = ap.parse_args(argv)

    catalog_path = Path(args.catalog)
    if not catalog_path.is_file():
        print(f"FATAL: tool catalog not found at {catalog_path} — regenerate it "
              "(`hermeshost tools-catalog --format public --out …`).", file=sys.stderr)
        return 2
    catalog = _load_catalog(catalog_path)

    report: dict[str, list[str]] = {}
    warns: dict[str, list[str]] = {}
    ok = True
    for b in args.bundles:
        bp = Path(b)
        violations, warnings = lint_bundle(bp, catalog)
        report[bp.name] = violations
        warns[bp.name] = warnings
        if violations:
            ok = False

    if args.json:
        print(json.dumps({"ok": ok, "violations": report, "warnings": warns}, indent=2))
    else:
        for name, violations in report.items():
            if violations:
                print(f"FAIL {name}:")
                for v in violations:
                    print(f"  - {v}")
            else:
                print(f"PASS {name}")
            for w in warns[name]:
                print(f"  WARN: {w}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
