"""The generated tool artifacts stay consistent with each other (stdlib-only).

The catalog (tools-catalog.json) says WHICH tools exist; the reference
(tools-reference.md + tools-contracts.json) is the authoring CONTRACT. All three
are generated by the platform from one source — this test catches a PARTIAL
regeneration (one file updated, its siblings stale), which would hand an author
a tool with no contract or a contract for a tool that no longer exists.
"""

from __future__ import annotations

import json
from pathlib import Path

REFS = Path(__file__).resolve().parents[1] / "skills" / "talent-authoring-standard" / "references"


def _catalog_names() -> set[str]:
    doc = json.loads((REFS / "tools-catalog.json").read_text())
    return {t["name"] for t in doc["tools"]}


def _contracts() -> dict:
    return json.loads((REFS / "tools-contracts.json").read_text())


def test_every_catalog_tool_has_a_contract_entry():
    contract_names = {t["name"] for t in _contracts()["tools"]}
    missing = _catalog_names() - contract_names
    assert not missing, (
        f"tools in the catalog but not in tools-contracts.json: {sorted(missing)} — "
        "regenerate BOTH artifacts together"
    )


def test_no_orphan_contract_entries():
    orphans = {t["name"] for t in _contracts()["tools"]} - _catalog_names()
    assert not orphans, (
        f"contracts for tools not in the catalog: {sorted(orphans)} — "
        "regenerate BOTH artifacts together"
    )


def test_reference_markdown_covers_every_tool():
    md = (REFS / "tools-reference.md").read_text()
    missing = [n for n in sorted(_catalog_names()) if f"`{n}`" not in md]
    assert not missing, (
        f"tools missing from tools-reference.md: {missing} — regenerate it"
    )


def test_contract_examples_parse_and_first_party_tools_have_them():
    for t in _contracts()["tools"]:
        if t["example_request"]:
            args = json.loads(t["example_request"])
            assert isinstance(args, dict), t["name"]
            props = (t.get("parameters") or {}).get("properties") or {}
            if props:
                unknown = [k for k in args if k not in props]
                assert not unknown, f"{t['name']}: example uses undeclared args {unknown}"
        else:
            assert t["request_via"] == "toolset_contribution", (
                f"{t['name']}: a first-party tool must carry a worked example"
            )


def test_generated_artifacts_carry_no_internal_vocabulary():
    blob = (REFS / "tools-reference.md").read_text() + (
        REFS / "tools-contracts.json"
    ).read_text()
    for banned in ("HermesHost", "tailscale", "Tailscale"):
        assert banned not in blob, f"internal term {banned!r} leaked into a generated artifact"
